import { Metadata } from "next";
import "./style.css"

export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by Nishad Koormath",
};
export default function About() {
  return (
    <>
      <div className="about-container mt-5">
        <h1 className="about-title">About Us</h1>
        <p className="about-description">
          Welcome to <strong>E-commerce</strong>, your one-stop destination
          for a wide range of products. Our platform is built to provide you
          with an exceptional shopping experience, combining convenience,
          affordability, and quality.
        </p>
        <div className="mission-section">
          <h2>Our Mission</h2>
          <p>
            To redefine online shopping by offering an extensive product
            catalog, secure transactions, and top-notch customer support. We aim
            to connect customers with products that enhance their lives and
            bring value to their everyday experiences.
          </p>
        </div>
        <div className="team-section">
          <h2>Our Team</h2>
          <p>
            Behind <strong>E-commerce</strong> is a dedicated team of
            developers, designers, and customer support specialists working
            tirelessly to improve your shopping journey.
          </p>
        </div>
        <div className="values-section">
          <h2>Our Core Values</h2>
          <ul>
            <li>Customer Satisfaction: Your happiness is our priority.</li>
            <li>
              Integrity: Transparent and ethical practices in every aspect.
            </li>
            <li>
              Innovation: Continuously improving our platform to serve you
              better.
            </li>
          </ul>
        </div>
      </div>
    </>
  );
}
