import Link from "next/link";
import { ProductService } from "./services/ProductServices";
import "./style.css"; // Make sure this file includes the styles
import { Product } from "./types/inference";
import Image from "next/image";
import { Suspense } from "react";
import ProductListSkeleton from "./components/ProductLodingSkelton";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "E-commerce | Home ",
  description: "Generated by Nishad Koormath",
};

const HomePage = async () => {
  // Fetch the products directly
  const fetchedProducts = await ProductService.getProducts("/products");
  const products = fetchedProducts.slice(-3); // Get the last 3 products

  return (
    <div className="container">
      <header className="header">
        <h1 className="title">Welcome to E-Commerce</h1>
      </header>

      <section className="featured-section">
        <h2 className="section-title">Featured Products</h2>
        <div className="product-grid">
          <Suspense fallback={<ProductListSkeleton />}>
            {products && products.length > 0 ? (
              products.map((p: Product) => (
                <div className="product-card" key={p.id}>
                  <Image
                    src={p.image || "https://via.placeholder.com/150"} // Fallback image
                    alt={p.title}
                    className="product-image"
                    style={{ objectFit: "contain" }}
                    width={100}
                    height={200}
                  />
                  <Link href={`/products/${p.id}`} className="title-link">
                    <h3 className="product-title">{p.title}</h3>
                  </Link>
                  <p className="product-price">{`$${p.price.toFixed(2)}`}</p>
                </div>
              ))
            ) : (
              <p>No featured products available.</p>
            )}
          </Suspense>
        </div>
      </section>
    </div>
  );
};

export default HomePage;
